apiVersion: microcumul.us/v1beta1
kind: ClusterOAuth2ClientProvider
metadata:
  name: keycloak
spec:
  keycloak:
    baseURL: http://keycloak-1630347783
    realm: master
    userAuth:
      username: user
      password:
        name: microcumulus-keycloak
        key: admin-password
        namespace: keycloak
---
apiVersion: microcumul.us/v1beta1
kind: OAuth2Client
metadata:
  name: test-1
  namespace: oauth2-proxy-controller-system
spec:
  provider:
    namespace: oauth2-proxy-controller-system
    name: keycloak
  clientName: test
  secretName: testclient
  redirects:
    - 'http://localhost:8080'
