resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:0fae259957a147aad65dfbe01da9fc19537bdd2cf51e8edf18a064dc68adb164
  name: controller
  newName: andrewstuart/oauth2controller
