resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:4d8448eee147c9ff10c66e92457805003356339b44955bde2e9a08091fc068a0
  name: controller
  newName: andrewstuart/oauth2controller
