resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:04be29deda382eb31f87b2560a1d0b2c01136a162fd63667bc03fe8d3d47648b
  name: controller
  newName: andrewstuart/oauth2controller
