resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a7074590b7fca0f4e283c1994a4ab58c0b3ed29180514b76b1d204f1d3115841
  name: controller
  newName: andrewstuart/oauth2controller
