resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:4180de83f08bf16d8b17744af261b52a67857b55c1bfcdcba9c02e05553c6fca
  name: controller
  newName: andrewstuart/oauth2controller
