resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a9e00970419cc4eb6047cf6813006e34b538d8add7dcfd6a02f63c40eeb2e59d
  name: controller
  newName: andrewstuart/oauth2controller
