resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:248aa5bd6e0dffb27c75717b2abc458408f8846384d8836f984e48ca210565ce
  name: controller
  newName: andrewstuart/oauth2controller
