resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ef077d66beddc9a7416b7f3da1cb8e10ada12c5f81613e1170c431578a0a283d
  name: controller
  newName: andrewstuart/oauth2controller
