resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ec242af7ee8b54d69068afb0e5acf6e20c0eb26c257141a656e376da3a8116c6
  name: controller
  newName: andrewstuart/oauth2controller
