resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:90165e957a91eaf8842a793b4497a3685342a766a798202a9470ecfab28eceb9
  name: controller
  newName: andrewstuart/oauth2controller
