resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d778dec6b218760df9e143cc16c1673fa0ff6526e6f8491c23fdd5ee05308810
  name: controller
  newName: andrewstuart/oauth2controller
