resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8a507278346e7881f6c3390225675809b518ccf6355048b47e1a22bbd066bb85
  name: controller
  newName: andrewstuart/oauth2controller
