resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:6dc09b62a647c1c181898295ba51d994b2200ee6960a354c412732201fb7e11b
  name: controller
  newName: andrewstuart/oauth2controller
