resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b29d14067d9b37a7ba561822447ffff8638c9ba3aed83e7919f21bbf043235a9
  name: controller
  newName: andrewstuart/oauth2controller
