# permissions for end users to view clusteroauth2clientproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusteroauth2clientprovider-viewer-role
rules:
- apiGroups:
  - microcumul.us.my.domain
  resources:
  - clusteroauth2clientproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microcumul.us.my.domain
  resources:
  - clusteroauth2clientproviders/status
  verbs:
  - get
