# permissions for end users to edit oauth2clients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauth2client-editor-role
rules:
- apiGroups:
  - microcumul.us
  resources:
  - oauth2clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microcumul.us
  resources:
  - oauth2clients/status
  verbs:
  - get
