# permissions for end users to view oauth2clients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauth2client-viewer-role
rules:
- apiGroups:
  - microcumul.us.my.domain
  resources:
  - oauth2clients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microcumul.us.my.domain
  resources:
  - oauth2clients/status
  verbs:
  - get
