# permissions for end users to view oauth2clientproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauth2clientprovider-viewer-role
rules:
- apiGroups:
  - microcumul.us
  resources:
  - oauth2clientproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microcumul.us
  resources:
  - oauth2clientproviders/status
  verbs:
  - get
