# permissions for end users to view oauth2proxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauth2proxy-viewer-role
rules:
- apiGroups:
  - microcumul.us
  resources:
  - oauth2proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microcumul.us
  resources:
  - oauth2proxies/status
  verbs:
  - get
